# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3478bad4da809b768768241605892f26e4ef20451d2b10f5f452419ec14c3fdbee800be4c22caf55fe5dea27abd72531d947cdc98037755c3d93962ee0409d68

test:
  secret_key_base: 910be5d37794f41c797998c0085449b900a3ea8f3efadf739794629554109469fae92b78242d1e339e81f9d2eafd8d67842dd7d279766c66cc987fec955fc601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
